export const ADD_EXAMINE = "EXAMINEs/ADD_EXAMINE" as const
export const FETCH_EXAMINES_STARTED = "EXAMINEs/FETCH_EXAMINES_STARTED" as const
export const FETCH_EXAMINES_SUCCEED = "EXAMINEs/FETCH_EXAMINES_SUCCEED" as const
export const FETCH_EXAMINES_FAILED = "EXAMINEs/FETCH_EXAMINES_FAILED" as const
